title: Notas
description: >- # this means to ignore newlines until "baseurl:"
  Notas, scripts y algoritmos de uso diario.
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
